/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ComponentsRouteImport } from './routes/components'
import { Route as CanvasWorkflowIdIndexRouteImport } from './routes/canvas/$workflowId/index'
import { Route as CanvasWorkflowIdAssetsRouteImport } from './routes/canvas/$workflowId/assets'
import { Route as CanvasWorkflowIdSettingsRouteImport } from './routes/canvas/$workflowId/settings'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ComponentsRoute = ComponentsRouteImport.update({
  id: '/components',
  path: '/components',
  getParentRoute: () => rootRouteImport,
} as any)
const CanvasWorkflowIdIndexRoute = CanvasWorkflowIdIndexRouteImport.update({
  id: '/canvas/$workflowId/',
  path: '/canvas/$workflowId/',
  getParentRoute: () => rootRouteImport,
} as any)
const CanvasWorkflowIdAssetsRoute = CanvasWorkflowIdAssetsRouteImport.update({
  id: '/canvas/$workflowId/assets',
  path: '/canvas/$workflowId/assets',
  getParentRoute: () => rootRouteImport,
} as any)
const CanvasWorkflowIdSettingsRoute =
  CanvasWorkflowIdSettingsRouteImport.update({
    id: '/canvas/$workflowId/settings',
    path: '/canvas/$workflowId/settings',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/components': typeof ComponentsRoute
  '/canvas/$workflowId/assets': typeof CanvasWorkflowIdAssetsRoute
  '/canvas/$workflowId/settings': typeof CanvasWorkflowIdSettingsRoute
  '/canvas/$workflowId/': typeof CanvasWorkflowIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/components': typeof ComponentsRoute
  '/canvas/$workflowId/assets': typeof CanvasWorkflowIdAssetsRoute
  '/canvas/$workflowId/settings': typeof CanvasWorkflowIdSettingsRoute
  '/canvas/$workflowId': typeof CanvasWorkflowIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/components': typeof ComponentsRoute
  '/canvas/$workflowId/assets': typeof CanvasWorkflowIdAssetsRoute
  '/canvas/$workflowId/settings': typeof CanvasWorkflowIdSettingsRoute
  '/canvas/$workflowId/': typeof CanvasWorkflowIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/components'
    | '/canvas/$workflowId/assets'
    | '/canvas/$workflowId/settings'
    | '/canvas/$workflowId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/components'
    | '/canvas/$workflowId/assets'
    | '/canvas/$workflowId/settings'
    | '/canvas/$workflowId'
  id:
    | '__root__'
    | '/'
    | '/components'
    | '/canvas/$workflowId/assets'
    | '/canvas/$workflowId/settings'
    | '/canvas/$workflowId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ComponentsRoute: typeof ComponentsRoute
  CanvasWorkflowIdAssetsRoute: typeof CanvasWorkflowIdAssetsRoute
  CanvasWorkflowIdSettingsRoute: typeof CanvasWorkflowIdSettingsRoute
  CanvasWorkflowIdIndexRoute: typeof CanvasWorkflowIdIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/components': {
      id: '/components'
      path: '/components'
      fullPath: '/components'
      preLoaderRoute: typeof ComponentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/canvas/$workflowId/': {
      id: '/canvas/$workflowId/'
      path: '/canvas/$workflowId'
      fullPath: '/canvas/$workflowId/'
      preLoaderRoute: typeof CanvasWorkflowIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/canvas/$workflowId/assets': {
      id: '/canvas/$workflowId/assets'
      path: '/canvas/$workflowId/assets'
      fullPath: '/canvas/$workflowId/assets'
      preLoaderRoute: typeof CanvasWorkflowIdAssetsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/canvas/$workflowId/settings': {
      id: '/canvas/$workflowId/settings'
      path: '/canvas/$workflowId/settings'
      fullPath: '/canvas/$workflowId/settings'
      preLoaderRoute: typeof CanvasWorkflowIdSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ComponentsRoute: ComponentsRoute,
  CanvasWorkflowIdAssetsRoute: CanvasWorkflowIdAssetsRoute,
  CanvasWorkflowIdSettingsRoute: CanvasWorkflowIdSettingsRoute,
  CanvasWorkflowIdIndexRoute: CanvasWorkflowIdIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
