import {
  WorkflowConflictError,
  WorkflowRunError,
} from '@red-video-flow/local-backend'
import type { IncomingMessage, ServerResponse } from 'node:http'
import type { LocalServerRuntime } from './runtime.js'
import { HttpError, sendJson } from './http.js'
import { handlePluginRoutes } from './routes/pluginRoutes.js'
import { handleDiscoveryRoutes } from './routes/discoveryRoutes.js'
import { handleWorkflowRoutes } from './routes/workflowRoutes.js'
import { handleAssetRoutes } from './routes/assetRoutes.js'
import { handleRunRoutes } from './routes/runRoutes.js'
import { handleStaticRoutes } from './routes/staticRoutes.js'
import { handleChatRoutes } from './routes/chatRoutes.js'
import { handleWorkflowAppRoutes } from './routes/workflowAppRoutes.js'
import { handleDefaultModelRoutes } from './routes/defaultModelRoutes.js'
import { handlePiAgentRoutes } from './routes/piAgentRoutes.js'
import { handleResourceRoutes } from './routes/resourceRoutes.js'
import { handleCredentialRoutes } from './routes/credentialRoutes.js'
import { handleHealthRoutes } from './routes/healthRoutes.js'

type RequestHandlerOptions = {
  webFallback?: (req: IncomingMessage, res: ServerResponse) => void
}

export function createRequestHandler(
  runtime: LocalServerRuntime,
  options: RequestHandlerOptions = {},
) {
  return async (req: IncomingMessage, res: ServerResponse) => {
    try {
      if (!isAllowedOrigin(req.headers.origin)) {
        sendJson(res, 403, { error: 'cross-origin access is restricted to localhost' })
        return
      }
      if (req.method === 'OPTIONS') {
        res.writeHead(204, {
          'Access-Control-Allow-Origin': '*',
          'Access-Control-Allow-Headers': 'content-type',
          'Access-Control-Allow-Methods': 'GET,POST,PUT,PATCH,DELETE,OPTIONS',
        })
        res.end()
        return
      }

      const url = new URL(req.url ?? '/', `http://${req.headers.host ?? '127.0.0.1'}`)
      const context = { req, res, url, pathname: url.pathname }
      const handlers = [
        handleHealthRoutes,
        handlePiAgentRoutes,
        handleDefaultModelRoutes,
        handleCredentialRoutes,
        handlePluginRoutes,
        handleDiscoveryRoutes,
        handleWorkflowRoutes,
        handleResourceRoutes,
        handleAssetRoutes,
        handleRunRoutes,
        handleWorkflowAppRoutes,
        handleChatRoutes,
      ]

      for (const handler of handlers) {
        if (await handler(runtime, context)) {
          await runtime.flushPersistence()
          return
        }
      }
      if (url.pathname.startsWith('/api/')) {
        sendJson(res, 404, { error: 'not found' })
        return
      }
      if (runtime.config.webMode === 'static' && await handleStaticRoutes(runtime, context)) return
      if (options.webFallback) {
        options.webFallback(req, res)
        return
      }
      sendJson(res, 404, { error: 'not found' })
    } catch (error) {
      if (!res.headersSent) {
        if (error instanceof HttpError) {
          sendJson(res, error.status, { error: error.message })
          return
        }
        if (error instanceof WorkflowConflictError) {
          sendJson(res, 409, { error: error.message, currentRevision: error.currentRevision })
          return
        }
        if (error instanceof WorkflowRunError) {
          sendJson(res, 400, { error: error.message })
          return
        }
        sendJson(res, 500, { error: error instanceof Error ? error.message : String(error) })
        return
      }
      res.write(`data: ${JSON.stringify({
        type: 'error',
        message: error instanceof Error ? error.message : String(error),
      })}\n\n`)
      res.end()
    }
  }
}

export function isAllowedOrigin(origin: string | undefined) {
  if (!origin) return true
  // Browsers serialize requests from locally opened file:// applications as
  // `Origin: null`. The server only listens locally, so permit that origin for
  // standalone HTML apps generated by a local Agent CLI.
  if (origin === 'null') return true
  try {
    const hostname = new URL(origin).hostname
    return hostname === 'localhost' || hostname === '127.0.0.1' || hostname === '[::1]'
  } catch {
    return false
  }
}
