export const builtinVisualModels = {
  models: [
    {
      id: 'gpt-image-2',
      label: 'GPT Image 2',
      vendor: 'OpenAI',
      available: true,
      invokable: true,
      binPath: null,
      capabilities: ['text-to-image', 'image-to-image'],
      pluginId: 'builtin.visual-gpt-image',
      optionsSchema: {
        type: 'object',
        properties: {
          action: { type: 'string', title: '生成方式', enum: ['auto', 'generate', 'edit'], enumNames: ['自动', '生成', '编辑'], default: 'auto' },
          size: { type: 'string', title: '尺寸', enum: ['auto', '1024x1024', '1536x1024', '1024x1536'], default: 'auto' },
          quality: { type: 'string', title: '质量', enum: ['auto', 'low', 'medium', 'high'], default: 'auto' },
          background: { type: 'string', title: '背景', enum: ['auto', 'opaque', 'transparent'], default: 'auto' },
          outputFormat: { type: 'string', title: '输出格式', enum: ['png', 'jpeg', 'webp'], default: 'png' },
          outputCompression: { type: 'integer', title: '压缩质量', minimum: 0, maximum: 100, default: 100, advanced: true },
          inputFidelity: { type: 'string', title: '输入保真度', enum: ['low', 'high'], default: 'low', advanced: true },
          moderation: { type: 'string', title: '内容审核', enum: ['auto', 'low'], default: 'auto', advanced: true },
        },
      },
    },
    {
      id: 'doubao-seedance-2',
      label: '豆包 Seedance 2.0',
      vendor: 'ByteDance',
      available: true,
      invokable: true,
      binPath: null,
      capabilities: ['text-to-video', 'image-to-video'],
      pluginId: 'builtin.visual-seedance',
      optionsSchema: {
        type: 'object',
        properties: {
          ratio: { type: 'string', title: '画面比例', enum: ['adaptive', '16:9', '9:16', '4:3', '3:4', '1:1', '21:9'], default: 'adaptive' },
          duration: {
            type: 'integer',
            title: '时长（秒）',
            enum: [-1, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15],
            enumNames: ['自动', '4 秒', '5 秒', '6 秒', '7 秒', '8 秒', '9 秒', '10 秒', '11 秒', '12 秒', '13 秒', '14 秒', '15 秒'],
            default: 5,
          },
          resolution: { type: 'string', title: '分辨率', enum: ['480p', '720p', '1080p'], default: '720p' },
          generate_audio: { type: 'boolean', title: '生成音频', default: true },
          camera_fixed: { type: 'boolean', title: '固定镜头', default: false, advanced: true },
          watermark: { type: 'boolean', title: '添加水印', default: false },
          seed: { type: 'integer', title: '随机种子', minimum: -1, maximum: 4294967295, default: -1 },
          return_last_frame: { type: 'boolean', title: '返回尾帧', default: false },
          callback_url: { type: 'string', title: '回调地址', advanced: true },
        },
      },
    },
  ],
  installedCount: 2,
  invokableCount: 2,
} as const
